### ISSUE TITLE
constant 4294967295 overflows int

### ISSUE THREAD

**Issue by emprovements** [maximeh/mkpimage#1]
Hi,
I just tried to build it via build.sh and i got this error.
./mkpimage.go:100: constant 4294967295 overflows int
./mkpimage.go:101: constant 4294967295 overflows int
install: cannot stat `mkpimage': No such file or directory

I dont know Go language but I checked it and it is in function 
func computeCRCChecksum(checksum_data []byte) uint32{

Machine is Xubuntu 12.04 
go version go1.1.1 linux/386

**Comment by maximeh** [comment]
It's because you have a 32bit machine. You'll need a 64bits one.

**Comment by nuxeh** [comment]
Does this tool not work on 32-bit then?

**Comment by emprovements** [comment]
Looks like no.

**Comment by maximeh** [comment]
If you have any interests, I have other versions of it in python, also in C (available in the sources of U-Boot), which should work with 32bits machines.

I don't have one at hand anymore so I can't really test that.

**Comment by emprovements** [comment]
The one in python would be interesting as well as in C :)

**Comment by nuxeh** [comment]
Also, just found this, which fixes for 32 bit for this version:
https://github.com/Lefinnois/mkpimage/commit/1922e4b0f446e8db01c3a784d52a6f65b460de5b

**Comment by maximeh** [comment]
Ah! Never knew about that fix. As a matter of fact, I don't use this tool anymore, I use the one integrated into Barebox a while after I did mine:

http://git.pengutronix.de/?p=barebox.git;a=blob;f=scripts/socfpga_mkimage.c;h=bab1b1abceb5998dba002319596828f1ce906276;hb=HEAD
